# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24eecb933896215a4054605edf3246ed4e9be4f6b1c0162b10752d4f0308064fe1bdd68771a44e5a13218b3c18da6119e722e31a265833bf0ae4b5b6b438ccea

test:
  secret_key_base: 944887de273308060164c8f62e887a2671f795117a52a8211efd69544dd2fac0d94230f32903b4f5aedb845e1f306287e8f90bb9528e795992dc9d8a92078481

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
